---
- name: Get the current kernel release.
  command: uname -r
  changed_when: false
  register: kernel_release

- name: Set the appropriate libselinux package for RHEL 8.
  set_fact:
    packer_rhel_libselinux_package: python3-libselinux
  when: ansible_distribution_major_version == '8'

- name: Ensure necessary packages are installed.
  yum:
    name:
      - wget
      - perl
      - cpp
      - gcc
      - make
      - bzip2
      - kernel-headers
      - kernel-devel
      - "kernel-devel-{{ kernel_release.stdout }}"
      - "{{ packer_rhel_libselinux_package }}"
      - elfutils-libelf-devel
      - cifs-utils
    state: present

# Fix slow DNS.
- name: Fix slow DNS (adapted from Bento).
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^RES_OPTIONS'
    line: 'RES_OPTIONS="single-request-reopen"'
    state: present

- name: Restart network service (RHEL < 8).
  service: name=network state=restarted
  when: ansible_distribution_major_version < '8'

# SSH daemon configuration.
- name: Configure SSH daemon.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^UseDNS', line: 'UseDNS no' }
    - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

# Vagrant SSH configuration.
- name: Configure Vagrant .ssh directory.
  file:
    path: /home/vagrant/.ssh
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0700

- name: Write Vagrant's public key to file.
  shell: echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key' > /home/vagrant/.ssh/authorized_keys

- name: Edit permissions on authorized_keys file.
  file:
    path: /home/vagrant/.ssh/authorized_keys
    state: file
    owner: vagrant
    group: vagrant
    mode: 0600

# VirtualBox tools installation.
- name: Check if VirtualBox is running the guest VM.
  stat: path=/home/vagrant/.vbox_version
  register: virtualbox_check

- include_tasks: virtualbox.yml
  when: virtualbox_check.stat.exists

# VMware tools installation.
- name: Check if VMWare is running the guest VM.
  shell: "cat /proc/scsi/scsi | grep VMware"
  changed_when: false
  failed_when: false
  register: vmware_check

- include_tasks: vmware.yml
  when: vmware_check.rc == 0

# Cleanup tasks.
- name: Remove unneeded packages.
  yum:
    name:
      - cpp
      - kernel-devel
      - kernel-headers
    state: absent

- name: Clean up yum.
  command: >
    yum clean all
    warn=false
  changed_when: true

- name: Remove any remnants of VirtualBox ISOs.
  shell: >
    rm -rf VBoxGuestAdditions_*.iso VBoxGuestAdditions_*.iso.?
    warn=false
  tags: ['skip_ansible_lint']

- name: Remove RedHat interface persistence (step 1).
  command: >
    rm -f /etc/udev/rules.d/70-persistent-net.rules
    warn=false
  tags: ['skip_ansible_lint']

- name: Remove RedHat interface persistence (step 2).
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: "{{ item }}"
    state: absent
  with_items:
    - '^HWADDR'
    - '^UUID'
